// Code generated by protoc-gen-routes. DO NOT EDIT.
// source: test.proto

package example

import "github.com/go-core-stack/auth/model"

var RoutesHelloWorld = []*model.Route{}

func init() {

	RoutesHelloWorld = append(RoutesHelloWorld, model.NewRoute("/v1/object/{name}", "POST"))

}
