// Code generated by protoc-gen-routes. DO NOT EDIT.
// source: test.proto

package example

import "github.com/go-core-stack/auth/model"

var RoutesHelloWorld = []*model.Route{}

func init() {
	var route *model.Route

	// Adding Route information for PostObject RPC
	route = model.NewRoute("/v1/object/{name}", "POST")
	route.Resource = "object"
	route.Scopes = append(route.Scopes, "abc")
	route.Scopes = append(route.Scopes, "def")
	route.Verb = "create"
	RoutesHelloWorld = append(RoutesHelloWorld, route)
}
